# Generated by Django 5.1.2 on 2025-07-06 03:59

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='activation_key',
            field=models.CharField(default=None, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='key_expires',
            field=models.IntegerField(blank=True, default=time.time),
        ),
    ]
