# Generated by Django 5.1.2 on 2025-07-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_activation_key_teacher_authorized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
