# Generated by Django 5.1.2 on 2025-05-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
