# Generated by Django 5.1.2 on 2025-07-07 21:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='url2',
            field=models.CharField(default=False, max_length=256),
        ),
        migrations.AddField(
            model_name='teacher',
            name='games',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
    ]
