# Generated by Django 5.1.2 on 2025-06-20 16:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_superuserform'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='games',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='SuperuserForm',
        ),
    ]
