# Generated by Django 5.1.2 on 2025-10-01 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_game_created_game_url2_teacher_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
