# Generated by Django 5.1.2 on 2025-10-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_game_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
