# Generated by Django 5.1.2 on 2025-06-20 17:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
    ]
