# Generated by Django 5.1.2 on 2025-06-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_game_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default=False, max_length=256),
        ),
    ]
