# Generated by Django 5.1.2 on 2025-10-01 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_remove_game_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
