# Generated by Django 5.1.2 on 2025-06-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.CharField(default=False, max_length=256),
        ),
    ]
