# Generated by Django 5.1.2 on 2025-10-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_game_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='teacher',
        ),
    ]
