# Generated by Django 5.1.2 on 2025-10-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_remove_game_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='url2',
        ),
    ]
