# Generated by Django 5.1.2 on 2025-10-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_remove_game_url2'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
