# Generated by Django 5.1.2 on 2025-10-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='random',
            field=models.BooleanField(default=False),
        ),
    ]
