# Generated by Django 5.1.2 on 2025-10-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_teacher_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='random',
        ),
    ]
