# Generated by Django 5.1.2 on 2025-10-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_remove_teacher_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='passwordsFinished',
            field=models.BooleanField(default=False),
        ),
    ]
