# Generated by Django 5.1.2 on 2025-10-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_game_passwordsfinished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
