# Generated by Django 5.1.2 on 2025-10-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_remove_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
