# Generated by Django 5.1.2 on 2025-10-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(blank=True),
        ),
    ]
