# Generated by Django 5.1.2 on 2025-10-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_teacher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=1, verbose_name='Week Limit')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='weekLimit',
            field=models.IntegerField(default=6),
        ),
    ]
