# Generated by Django 5.1.2 on 2025-12-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_alter_weekentries_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
