# Generated by Django 5.1.2 on 2026-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_alter_teacher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogenCost', models.FloatField(choices=[(0.5, 0.5), (0.55, 0.55), (0.6, 0.6), (0.65, 0.65), (0.7, 0.7), (0.75, 0.75), (0.8, 0.8), (0.85, 0.85), (0.9, 0.9), (0.95, 0.95), (1.0, 1.0), (1.05, 1.05), (1.1, 1.1), (1.15, 1.15), (1.2, 1.2), (1.25, 1.25), (1.3, 1.3), (1.35, 1.35), (1.4, 1.4), (1.45, 1.45), (1.5, 1.5)], default=0.5, verbose_name='Fertilizer Cost')),
            ],
        ),
    ]
