# Generated by Django 5.1.2 on 2026-04-10 17:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_gamesetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetup',
            name='cornPrice',
            field=models.DecimalField(choices=[(Decimal('3.5'), '3.5'), (Decimal('3.6'), '3.6'), (Decimal('3.7'), '3.7'), (Decimal('3.8'), '3.8'), (Decimal('3.9'), '3.9'), (Decimal('4.0'), '4.0'), (Decimal('4.1'), '4.1'), (Decimal('4.2'), '4.2'), (Decimal('4.3'), '4.3'), (Decimal('4.4'), '4.4'), (Decimal('4.5'), '4.5'), (Decimal('4.6'), '4.6'), (Decimal('4.7'), '4.7'), (Decimal('4.8'), '4.8'), (Decimal('4.9'), '4.9'), (Decimal('5.0'), '5.0'), (Decimal('5.1'), '5.1'), (Decimal('5.2'), '5.2'), (Decimal('5.3'), '5.3'), (Decimal('5.4'), '5.4'), (Decimal('5.5'), '5.5'), (Decimal('5.6'), '5.6'), (Decimal('5.7'), '5.7'), (Decimal('5.8'), '5.8'), (Decimal('5.9'), '5.9'), (Decimal('6.0'), '6.0'), (Decimal('6.1'), '6.1'), (Decimal('6.2'), '6.2'), (Decimal('6.3'), '6.3'), (Decimal('6.4'), '6.4'), (Decimal('6.5'), '6.5'), (Decimal('6.6'), '6.6'), (Decimal('6.7'), '6.7'), (Decimal('6.8'), '6.8'), (Decimal('6.9'), '6.9'), (Decimal('7.0'), '7.0'), (Decimal('7.1'), '7.1'), (Decimal('7.2'), '7.2'), (Decimal('7.3'), '7.3'), (Decimal('7.4'), '7.4'), (Decimal('7.5'), '7.5')], decimal_places=2, default=Decimal('3.5'), max_digits=4, verbose_name='Corn Price:'),
        ),
        migrations.AddField(
            model_name='gamesetup',
            name='irrigationCost',
            field=models.DecimalField(choices=[(Decimal('5.0'), '5.0'), (Decimal('5.5'), '5.5'), (Decimal('6.0'), '6.0'), (Decimal('6.5'), '6.5'), (Decimal('7.0'), '7.0'), (Decimal('7.5'), '7.5'), (Decimal('8.0'), '8.0'), (Decimal('8.5'), '8.5'), (Decimal('9.0'), '9.0'), (Decimal('9.5'), '9.5'), (Decimal('10.0'), '10.0'), (Decimal('10.5'), '10.5'), (Decimal('11.0'), '11.0'), (Decimal('11.5'), '11.5'), (Decimal('12.0'), '12.0'), (Decimal('12.5'), '12.5'), (Decimal('13.0'), '13.0'), (Decimal('13.5'), '13.5'), (Decimal('14.0'), '14.0'), (Decimal('14.5'), '14.5'), (Decimal('15.0'), '15.0')], decimal_places=2, default=Decimal('5.00'), max_digits=4, verbose_name='Irrigation Cost (per in.)'),
        ),
        migrations.AlterField(
            model_name='gamesetup',
            name='nitrogenCost',
            field=models.DecimalField(choices=[(Decimal('0.50'), '0.50'), (Decimal('0.55'), '0.55'), (Decimal('0.60'), '0.60'), (Decimal('0.65'), '0.65'), (Decimal('0.70'), '0.70'), (Decimal('0.75'), '0.75'), (Decimal('0.80'), '0.80'), (Decimal('0.85'), '0.85'), (Decimal('0.90'), '0.90'), (Decimal('0.95'), '0.95'), (Decimal('1.00'), '1.00'), (Decimal('1.05'), '1.05'), (Decimal('1.10'), '1.10'), (Decimal('1.15'), '1.15'), (Decimal('1.20'), '1.20'), (Decimal('1.25'), '1.25'), (Decimal('1.30'), '1.30'), (Decimal('1.35'), '1.35'), (Decimal('1.40'), '1.40'), (Decimal('1.45'), '1.45'), (Decimal('1.50'), '1.50')], decimal_places=2, default=Decimal('0.5'), max_digits=4, verbose_name='Fertilizer Cost (per lb.)'),
        ),
    ]
