# Generated by Django 5.1.2 on 2026-04-10 19:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_gamesetup_cornprice_gamesetup_irrigationcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cornPrice',
            field=models.FloatField(default=3.5),
        ),
        migrations.AddField(
            model_name='game',
            name='irrigationCost',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='game',
            name='nitrogenCost',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='gamesetup',
            name='cornPrice',
            field=models.DecimalField(choices=[(Decimal('3.5'), '$ 3.50'), (Decimal('3.6'), '$ 3.60'), (Decimal('3.7'), '$ 3.70'), (Decimal('3.8'), '$ 3.80'), (Decimal('3.9'), '$ 3.90'), (Decimal('4.0'), '$ 4.00'), (Decimal('4.1'), '$ 4.10'), (Decimal('4.2'), '$ 4.20'), (Decimal('4.3'), '$ 4.30'), (Decimal('4.4'), '$ 4.40'), (Decimal('4.5'), '$ 4.50'), (Decimal('4.6'), '$ 4.60'), (Decimal('4.7'), '$ 4.70'), (Decimal('4.8'), '$ 4.80'), (Decimal('4.9'), '$ 4.90'), (Decimal('5.0'), '$ 5.00'), (Decimal('5.1'), '$ 5.10'), (Decimal('5.2'), '$ 5.20'), (Decimal('5.3'), '$ 5.30'), (Decimal('5.4'), '$ 5.40'), (Decimal('5.5'), '$ 5.50'), (Decimal('5.6'), '$ 5.60'), (Decimal('5.7'), '$ 5.70'), (Decimal('5.8'), '$ 5.80'), (Decimal('5.9'), '$ 5.90'), (Decimal('6.0'), '$ 6.00'), (Decimal('6.1'), '$ 6.10'), (Decimal('6.2'), '$ 6.20'), (Decimal('6.3'), '$ 6.30'), (Decimal('6.4'), '$ 6.40'), (Decimal('6.5'), '$ 6.50'), (Decimal('6.6'), '$ 6.60'), (Decimal('6.7'), '$ 6.70'), (Decimal('6.8'), '$ 6.80'), (Decimal('6.9'), '$ 6.90'), (Decimal('7.0'), '$ 7.00'), (Decimal('7.1'), '$ 7.10'), (Decimal('7.2'), '$ 7.20'), (Decimal('7.3'), '$ 7.30'), (Decimal('7.4'), '$ 7.40'), (Decimal('7.5'), '$ 7.50')], decimal_places=2, default=Decimal('3.5'), max_digits=4, verbose_name='Corn Price:'),
        ),
        migrations.AlterField(
            model_name='gamesetup',
            name='irrigationCost',
            field=models.DecimalField(choices=[(Decimal('5.0'), '$ 5.00'), (Decimal('5.5'), '$ 5.50'), (Decimal('6.0'), '$ 6.00'), (Decimal('6.5'), '$ 6.50'), (Decimal('7.0'), '$ 7.00'), (Decimal('7.5'), '$ 7.50'), (Decimal('8.0'), '$ 8.00'), (Decimal('8.5'), '$ 8.50'), (Decimal('9.0'), '$ 9.00'), (Decimal('9.5'), '$ 9.50'), (Decimal('10.0'), '$ 10.00'), (Decimal('10.5'), '$ 10.50'), (Decimal('11.0'), '$ 11.00'), (Decimal('11.5'), '$ 11.50'), (Decimal('12.0'), '$ 12.00'), (Decimal('12.5'), '$ 12.50'), (Decimal('13.0'), '$ 13.00'), (Decimal('13.5'), '$ 13.50'), (Decimal('14.0'), '$ 14.00'), (Decimal('14.5'), '$ 14.50'), (Decimal('15.0'), '$ 15.00')], decimal_places=2, default=Decimal('5.00'), max_digits=4, verbose_name='Irrigation Cost (per in.)'),
        ),
        migrations.AlterField(
            model_name='gamesetup',
            name='nitrogenCost',
            field=models.DecimalField(choices=[(Decimal('0.50'), '$ 0.50'), (Decimal('0.55'), '$ 0.55'), (Decimal('0.60'), '$ 0.60'), (Decimal('0.65'), '$ 0.65'), (Decimal('0.70'), '$ 0.70'), (Decimal('0.75'), '$ 0.75'), (Decimal('0.80'), '$ 0.80'), (Decimal('0.85'), '$ 0.85'), (Decimal('0.90'), '$ 0.90'), (Decimal('0.95'), '$ 0.95'), (Decimal('1.00'), '$ 1.00'), (Decimal('1.05'), '$ 1.05'), (Decimal('1.10'), '$ 1.10'), (Decimal('1.15'), '$ 1.15'), (Decimal('1.20'), '$ 1.20'), (Decimal('1.25'), '$ 1.25'), (Decimal('1.30'), '$ 1.30'), (Decimal('1.35'), '$ 1.35'), (Decimal('1.40'), '$ 1.40'), (Decimal('1.45'), '$ 1.45'), (Decimal('1.50'), '$ 1.50')], decimal_places=2, default=Decimal('0.5'), max_digits=4, verbose_name='Fertilizer Cost (per lb.)'),
        ),
    ]
