# Generated by Django 5.1.2 on 2026-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_alter_gamesetup_cornprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cornPrice',
            field=models.FloatField(default=4.25),
        ),
        migrations.AlterField(
            model_name='game',
            name='irrigationCost',
            field=models.FloatField(default=6.5),
        ),
        migrations.AlterField(
            model_name='game',
            name='nitrogenCost',
            field=models.FloatField(default=0.6),
        ),
    ]
