# Generated by Django 5.1.2 on 2026-04-20 16:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_alter_game_cornprice_alter_game_irrigationcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='waterNitrates',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='gamesetup',
            name='waterNitrates',
            field=models.DecimalField(choices=[(Decimal('1'), '1.00'), (Decimal('2'), '2.00'), (Decimal('3'), '3.00'), (Decimal('4'), '4.00'), (Decimal('5'), '5.00'), (Decimal('6'), '6.00'), (Decimal('7'), '7.00'), (Decimal('8'), '8.00'), (Decimal('9'), '9.00'), (Decimal('10'), '10.00'), (Decimal('11'), '11.00'), (Decimal('12'), '12.00'), (Decimal('13'), '13.00'), (Decimal('14'), '14.00'), (Decimal('15'), '15.00'), (Decimal('16'), '16.00'), (Decimal('17'), '17.00'), (Decimal('18'), '18.00'), (Decimal('19'), '19.00'), (Decimal('20'), '20.00'), (Decimal('21'), '21.00'), (Decimal('22'), '22.00'), (Decimal('23'), '23.00'), (Decimal('24'), '24.00'), (Decimal('25'), '25.00'), (Decimal('26'), '26.00'), (Decimal('27'), '27.00'), (Decimal('28'), '28.00'), (Decimal('29'), '29.00'), (Decimal('30'), '30.00'), (Decimal('31'), '31.00'), (Decimal('32'), '32.00'), (Decimal('33'), '33.00'), (Decimal('34'), '34.00'), (Decimal('35'), '35.00'), (Decimal('36'), '36.00'), (Decimal('37'), '37.00'), (Decimal('38'), '38.00'), (Decimal('39'), '39.00'), (Decimal('40'), '40.00'), (Decimal('39'), '39.00'), (Decimal('40'), '40.00'), (Decimal('39'), '39.00'), (Decimal('40'), '40.00'), (Decimal('39'), '39.00'), (Decimal('40'), '40.00'), (Decimal('41'), '41.00'), (Decimal('42'), '42.00'), (Decimal('43'), '43.00'), (Decimal('44'), '44.00'), (Decimal('45'), '45.00'), (Decimal('46'), '46.00'), (Decimal('47'), '47.00'), (Decimal('48'), '48.00'), (Decimal('49'), '49.00'), (Decimal('50'), '50.00')], decimal_places=2, default=Decimal('25.0'), max_digits=4, verbose_name='Water Nitrates (ppm per in.)'),
        ),
    ]
