# Generated by Django 5.1.2 on 2026-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_game_waternitrates_gamesetup_waternitrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='weatherFile',
            field=models.CharField(default='NEME2101.WTH'),
        ),
        migrations.AddField(
            model_name='gamesetup',
            name='weatherFile',
            field=models.CharField(choices=[('NEME0401.WTH', '2004'), ('NEME0501.WTH', '2005'), ('NEME0601.WTH', '2006'), ('NEME0701.WTH', '2007'), ('NEME0801.WTH', '2008'), ('NEME0901.WTH', '2009'), ('NEME1001.WTH', '2010'), ('NEME1101.WTH', '2011'), ('NEME1201.WTH', '2012'), ('NEME1301.WTH', '2013'), ('NEME1401.WTH', '2014'), ('NEME1501.WTH', '2015'), ('NEME1601.WTH', '2016'), ('NEME1701.WTH', '2017'), ('NEME1801.WTH', '2018'), ('NEME1901.WTH', '2019'), ('NEME2001.WTH', '2020'), ('NEME2101.WTH', '2021'), ('NEME2201.WTH', '2022'), ('NEME2301.WTH', '2023'), ('NEME2401.WTH', '2024')], default='NEME2101.WTH', max_length=40, verbose_name='North Platte Weather:'),
        ),
    ]
