# Generated by Django 5.1.2 on 2026-04-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_game_weatherfile_gamesetup_weatherfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='otherCosts',
            field=models.DecimalField(decimal_places=2, default=742.79, max_digits=6),
        ),
        migrations.AddField(
            model_name='gamesetup',
            name='otherCosts',
            field=models.DecimalField(decimal_places=2, default=742.79, max_digits=6),
        ),
    ]
