# Generated by Django 5.1.2 on 2026-05-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0031_alter_gamesetup_weatherfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetup',
            name='forecasting',
            field=models.BooleanField(default=False, verbose_name='Forecast?'),
        ),
    ]
