# Generated by Django 5.1.2 on 2026-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0032_gamesetup_forecasting'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='waterLimit',
            field=models.CharField(default='unlimited'),
        ),
        migrations.AddField(
            model_name='gamesetup',
            name='waterLimit',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('unlimited', 'unlimited')], default='unlimited', max_length=40, verbose_name='Water Limit:'),
        ),
        migrations.AlterField(
            model_name='gamesetup',
            name='otherCosts',
            field=models.DecimalField(decimal_places=2, default=742.79, max_digits=6, verbose_name='Other Costs:'),
        ),
    ]
