# Generated by Django 5.1.2 on 2026-06-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0033_game_waterlimit_gamesetup_waterlimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesetup',
            name='waterLimit',
            field=models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), ('unlimited', 'unlimited')], default='unlimited', max_length=40, verbose_name='Water Limit:'),
        ),
    ]
