# Generated by Django 5.1.2 on 2026-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0034_alter_gamesetup_waterlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesetup',
            name='forecasting',
            field=models.BooleanField(default=True, verbose_name='Forecast?'),
        ),
        migrations.AlterField(
            model_name='gamesetup',
            name='waterLimit',
            field=models.CharField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5'), (5.5, '5.5'), (6, '6'), (6.5, '6.5'), (7, '7'), (7.5, '7.5'), (8, '8'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10'), (10.5, '10.5'), (11, '11'), (11.5, '11.5'), (12, '12'), (12.5, '12.5'), (13, '13'), (13.5, '13.5'), (14, '14'), (14.5, '14.5'), (15, '15'), ('unlimited', 'unlimited')], default='unlimited', max_length=40, verbose_name='Water Limit:'),
        ),
        migrations.AlterField(
            model_name='gamesetup',
            name='weatherFile',
            field=models.CharField(choices=[('Random', 'Random Weather'), ('NEME0401.WTH', '2004'), ('NEME0501.WTH', '2005'), ('NEME0601.WTH', '2006'), ('NEME0701.WTH', '2007'), ('NEME0801.WTH', '2008'), ('NEME0901.WTH', '2009'), ('NEME1001.WTH', '2010'), ('NEME1101.WTH', '2011'), ('NEME1201.WTH', '2012'), ('NEME1301.WTH', '2013'), ('NEME1401.WTH', '2014'), ('NEME1501.WTH', '2015'), ('NEME1601.WTH', '2016'), ('NEME1701.WTH', '2017'), ('NEME1801.WTH', '2018'), ('NEME1901.WTH', '2019'), ('NEME2001.WTH', '2020'), ('NEME2101.WTH', '2021'), ('NEME2201.WTH', '2022'), ('NEME2301.WTH', '2023'), ('NEME2401.WTH', '2024'), ('NEME2501.WTH', '2025')], default='NEME2101.WTH', max_length=40, verbose_name='North Platte Weather:'),
        ),
    ]
