# Generated by Django 5.1.2 on 2026-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0036_alter_gamesetup_waternitrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='waterNitrates',
            field=models.FloatField(default=0.0),
        ),
    ]
