# Generated by Django 5.1.2 on 2026-09-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0037_alter_game_waternitrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='initWeek',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesetup',
            name='startWeek',
            field=models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5'), (6, 'Week 6'), (7, 'Week 7'), (8, 'Week 8'), (9, 'Week 9'), (10, 'Week 10'), (11, 'Week 11'), (12, 'Week 12'), (13, 'Week 13'), (14, 'Week 14'), (15, 'Week 15'), (16, 'Week 16'), (17, 'Week 17'), (18, 'Week 18'), (19, 'Week 19'), (20, 'Week 20'), (21, 'Week 21')], default=1, verbose_name='Starting Week:'),
        ),
    ]
