# Generated by Django 5.1.2 on 2025-10-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_hiddenname_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hiddenName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
