# Generated by Django 5.1.2 on 2025-07-08 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='authorized',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='key_expires',
        ),
    ]
