# Generated by Django 5.1.2 on 2025-10-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_hiddenname_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hiddenName',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
