# Generated by Django 4.2.7 on 2024-01-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='hybrid',
            field=models.CharField(choices=[('BRPI0202', 'BRPI0202'), ('EBPL8501', 'EBPL8501'), ('FLSC8101', 'FLSC8101'), ('GAGR0201', 'GAGR0201')], default='BRPI0202', max_length=8),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
