# Generated by Django 4.2.7 on 2024-01-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0002_gamerprofile_age_gamerprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleplayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hybrid', models.CharField(choices=[('BRPI0202', 'BRPI0202'), ('EBPL8501', 'EBPL8501'), ('FLSC8101', 'FLSC8101'), ('GAGR0201', 'GAGR0201'), ('GHWA0401', 'GHWA0401'), ('IBWA8301', 'IBWA8301'), ('IUAF9901', 'IUAF9901'), ('SIAZ9601', 'SIAZ9601'), ('UFGA8201', 'UFGA8201')], default='BRPI0202', max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='GamerProfile',
        ),
    ]
