# Generated by Django 4.2.7 on 2024-02-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0003_singleplayerprofile_delete_gamerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleplayerprofile',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
