# Generated by Django 4.2.7 on 2024-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0004_singleplayerprofile_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertigationEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.IntegerField(default=0)),
                ('monday', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('tuesday', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('wednesday', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('thursday', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('friday', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('saturday', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('sunday', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
    ]
