# Generated by Django 4.2.7 on 2024-03-22 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0006_alter_fertigationentries_friday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tuesday', models.IntegerField()),
                ('wednesday', models.IntegerField()),
                ('thursday', models.IntegerField()),
                ('friday', models.IntegerField()),
                ('saturday', models.IntegerField()),
                ('sunday', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FertigationEntries',
        ),
    ]
