# Generated by Django 4.2.11 on 2024-06-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0008_fertilizerinit_alter_irrigationentries_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerinit',
            name='week10',
            field=models.IntegerField(default=0, verbose_name='V12 Fertigation (week 10)'),
        ),
        migrations.AddField(
            model_name='fertilizerinit',
            name='week12',
            field=models.IntegerField(default=0, verbose_name='VT Fertigation (week 12)'),
        ),
        migrations.AddField(
            model_name='fertilizerinit',
            name='week14',
            field=models.IntegerField(default=0, verbose_name='R2 Fertigation (week 14)'),
        ),
        migrations.AddField(
            model_name='fertilizerinit',
            name='week15',
            field=models.IntegerField(default=0, verbose_name='R3 Fertigation (week 15)'),
        ),
        migrations.AddField(
            model_name='fertilizerinit',
            name='week6',
            field=models.IntegerField(default=0, verbose_name='Side-Dress (week 6)'),
        ),
        migrations.AddField(
            model_name='fertilizerinit',
            name='week9',
            field=models.IntegerField(default=0, verbose_name='V9 Fertigation (week 9)'),
        ),
    ]
