# Generated by Django 4.2.11 on 2024-06-25 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0009_fertilizerinit_week10_fertilizerinit_week12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleplayerprofile',
            name='seeding_rate',
            field=models.IntegerField(choices=[(10000, 10000)], default=10000),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week1',
            field=models.IntegerField(default=0, verbose_name='Pre-plant Nitrogen, Week 1 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week10',
            field=models.IntegerField(default=0, verbose_name='V12 Fertigation Nitrogen, Week 10 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week12',
            field=models.IntegerField(default=0, verbose_name='VT Fertigation Nitrogen, Week 12 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week14',
            field=models.IntegerField(default=0, verbose_name='R2 Fertigation Nitrogen, Week 14 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week15',
            field=models.IntegerField(default=0, verbose_name='R3 Fertigation Nitrogen, Week 15 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week6',
            field=models.IntegerField(default=0, verbose_name='Side-Dress Nitrogen, Week 6 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week9',
            field=models.IntegerField(default=0, verbose_name='V9 Fertigation Nitrogen, Week 9 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='friday',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='saturday',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='sunday',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='thursday',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='tuesday',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='wednesday',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
    ]
