# Generated by Django 4.2.11 on 2024-06-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0010_singleplayerprofile_seeding_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleplayerprofile',
            name='weather_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Wet', 'Wet'), ('Dry', 'Dry')], default='Normal', max_length=6),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week1',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0, verbose_name='Pre-plant Nitrogen, Week 1 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week10',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='V12 Fertigation Nitrogen, Week 10 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week12',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='VT Fertigation Nitrogen, Week 12 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week14',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='R2 Fertigation Nitrogen, Week 14 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week15',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='R3 Fertigation Nitrogen, Week 15 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week6',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0, verbose_name='Side-Dress Nitrogen, Week 6 (lbs/acre)'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week9',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='V9 Fertigation Nitrogen, Week 9 (lbs/acre)'),
        ),
    ]
