# Generated by Django 5.0.1 on 2024-08-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0011_singleplayerprofile_weather_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleplayerprofile',
            name='seeding_rate',
            field=models.IntegerField(choices=[(24000, 24000), (26000, 26000), (28000, 28000), (30000, 30000), (32000, 32000), (34000, 34000), (36000, 36000), (38000, 38000), (40000, 40000), (42000, 42000)], default=10000),
        ),
    ]
