# Generated by Django 5.1.2 on 2025-02-18 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0013_singleplayerprofile_fert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationentries',
            name='friday',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='monday',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='saturday',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='sunday',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='thursday',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='tuesday',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
        migrations.AlterField(
            model_name='irrigationentries',
            name='wednesday',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
    ]
