# Generated by Django 5.1.2 on 2025-11-21 03:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0020_alter_weekentries_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerEntries1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerEntries2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerInit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week1', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0, verbose_name='Week 1, Pre-plant Nitrogen')),
                ('week6', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0, verbose_name='Week 6, Side-Dress Nitrogen')),
                ('week9', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 9, V9 Fertigation Nitrogen')),
                ('week10', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 10, V12 Fertigation Nitrogen')),
                ('week12', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 12, VT Fertigation Nitrogen')),
                ('week14', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 14, R2 Fertigation Nitrogen')),
                ('week15', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 15, R3 Fertigation Nitrogen')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], default=0)),
                ('thursday', models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hybrid', models.CharField(choices=[('IB2074 Channel213-19VTPRIB', 'Channel213-19VTPRIB'), ('PC0006 Fontanelle 11D637', 'Fontanelle 11D637'), ('IB2073 Pioneer 0801AM', 'Pioneer 0801AM'), ('IB2072 Pioneer 1197AM', 'Pioneer 1197AM'), ('IB1071 Pioneer 1366AML', 'Pioneer 1366AML'), ('IB1073 Pioneer 1185', 'Pioneer 1185AM')], default=None, max_length=30, null=True)),
                ('seeding_rate', models.IntegerField(choices=[(24000, 24000), (26000, 26000), (28000, 28000), (30000, 30000), (32000, 32000), (34000, 34000), (36000, 36000), (38000, 38000), (40000, 40000), (42000, 42000)], default=10000)),
                ('week', models.IntegerField(default=0)),
                ('fert_id', models.IntegerField(default=-1)),
                ('initialized', models.BooleanField(default=False)),
                ('computing', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('projected_yields', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, default=list, size=None)),
                ('monday_irrigation', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, default=list, size=None)),
                ('thursday_irrigation', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, default=list, size=None)),
                ('weekly_fertilizer', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, default=list, size=None)),
                ('total_cost', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
