# Generated by Django 5.1.2 on 2025-07-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerEntries1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerEntries2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerInit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week1', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0, verbose_name='Pre-plant Nitrogen, Week 1 (lbs/acre)')),
                ('week6', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0, verbose_name='Side-Dress Nitrogen, Week 6 (lbs/acre)')),
                ('week9', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='V9 Fertigation Nitrogen, Week 9 (lbs/acre)')),
                ('week10', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='V12 Fertigation Nitrogen, Week 10 (lbs/acre)')),
                ('week12', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='VT Fertigation Nitrogen, Week 12 (lbs/acre)')),
                ('week14', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='R2 Fertigation Nitrogen, Week 14 (lbs/acre)')),
                ('week15', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='R3 Fertigation Nitrogen, Week 15 (lbs/acre)')),
            ],
        ),
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hybrid', models.CharField(choices=[('MZCER048', 'MZCER048')], default='BRPI0202', max_length=8)),
                ('seeding_rate', models.IntegerField(choices=[(24000, 24000), (26000, 26000), (28000, 28000), (30000, 30000), (32000, 32000), (34000, 34000), (36000, 36000), (38000, 38000), (40000, 40000), (42000, 42000)], default=10000)),
                ('weather_type', models.CharField(choices=[('Normal', 'Normal'), ('Wet', 'Wet'), ('Dry', 'Dry')], default='Normal', max_length=6)),
                ('week', models.IntegerField(default=1)),
                ('fert_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], default=0)),
                ('thursday', models.FloatField(choices=[(0, 0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1, 1)], default=0)),
            ],
        ),
    ]
