# Generated by Django 5.1.2 on 2025-11-07 01:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='projected_yield',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='projected_yields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, default=list, size=None),
        ),
    ]
