# Generated by Django 5.1.2 on 2025-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='agronomic_efficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='irrigation_water_use_efficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='nitrogen_leaching',
            field=models.FloatField(default=0),
        ),
    ]
