# Generated by Django 5.1.2 on 2025-11-07 01:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gameprofile_projected_yield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='projected_yields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
    ]
