# Generated by Django 5.1.2 on 2025-12-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameprofile_agronomic_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='wnipi',
            field=models.FloatField(default=0),
        ),
    ]
