# Generated by Django 5.1.2 on 2025-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameprofile_hybrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
