# Generated by Django 5.1.2 on 2025-11-07 01:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameprofile_projected_yields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='projected_yields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, default=list, size=None),
        ),
    ]
