# Generated by Django 5.1.2 on 2025-09-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameprofile_computing_alter_gameprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='weather_type',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='team_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
