# Generated by Django 5.1.2 on 2026-01-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameprofile_nitrogenuseefficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='nitrogen_uptake',
            field=models.FloatField(default=0),
        ),
    ]
