# Generated by Django 5.1.2 on 2025-09-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_gameprofile_weather_type_gameprofile_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='team_id',
            field=models.IntegerField(blank=True),
        ),
    ]
