# Generated by Django 5.1.2 on 2026-01-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameprofile_nitrogen_uptake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='nitrogenUseEfficiency',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='partialFactorProductivity',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='waterProductivity',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='waterUseEfficiency',
            field=models.FloatField(default=-1),
        ),
    ]
