# Generated by Django 5.1.2 on 2026-02-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_gameprofile_nitrogenuseefficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='nitrogen_leaching_list',
            field=models.FloatField(default=0),
        ),
    ]
