# Generated by Django 5.1.2 on 2026-02-16 06:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gameprofile_nitrogen_leaching_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='nitrogen_leaching_list',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='nitrogen_leaching_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, default=list, size=None),
        ),
    ]
