# Generated by Django 5.1.2 on 2025-09-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_gameprofile_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
    ]
