# Generated by Django 5.1.2 on 2026-03-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_gameprofile_nitrogen_leaching_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='nitrogen_sufficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week1',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0, verbose_name='Week 1, At-plant Nitrogen'),
        ),
    ]
