# Generated by Django 5.1.2 on 2026-03-23 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gameprofile_nitrogen_sufficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='nitrogen_sufficiency_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, default=list, size=None),
        ),
    ]
