# Generated by Django 5.1.2 on 2025-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gameprofile_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
