# Generated by Django 5.1.2 on 2026-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gameprofile_nitrogen_sufficiency_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='cornPrice',
            field=models.FloatField(default=3.5),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='irrigationCost',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='nitrogenCost',
            field=models.FloatField(default=0.5),
        ),
    ]
