# Generated by Django 5.1.2 on 2025-09-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gameprofile_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
