# Generated by Django 5.1.2 on 2026-04-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gameprofile_cornprice_gameprofile_irrigationcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='cornPrice',
            field=models.FloatField(default=4.25),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='irrigationCost',
            field=models.FloatField(default=6.5),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='nitrogenCost',
            field=models.FloatField(default=0.6),
        ),
    ]
