# Generated by Django 5.1.2 on 2025-09-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_gameprofile_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
