# Generated by Django 5.1.2 on 2025-09-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_gameprofile_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
