# Generated by Django 5.1.2 on 2026-04-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_gameprofile_cornprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='waterNitrates',
            field=models.FloatField(default=25.0),
        ),
    ]
