# Generated by Django 5.1.2 on 2026-04-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_gameprofile_waternitrates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='cornPrice',
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='irrigationCost',
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='nitrogenCost',
        ),
        migrations.RemoveField(
            model_name='gameprofile',
            name='waterNitrates',
        ),
    ]
