# Generated by Django 5.1.2 on 2025-09-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_fertilizerinit_week1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='week',
            field=models.IntegerField(default=11),
        ),
    ]
