# Generated by Django 5.1.2 on 2026-06-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_remove_gameprofile_cornprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='waterLimit',
            field=models.CharField(default='unlimited'),
        ),
    ]
