# Generated by Django 5.1.2 on 2025-09-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_gameprofile_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week1',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0, verbose_name='Week 1, Pre-plant Nitrogen'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week10',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 10, V12 Fertigation Nitrogen'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week12',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 12, VT Fertigation Nitrogen'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week14',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 14, R2 Fertigation Nitrogen'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week15',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 15, R3 Fertigation Nitrogen'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week6',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180)], default=0, verbose_name='Week 6, Side-Dress Nitrogen'),
        ),
        migrations.AlterField(
            model_name='fertilizerinit',
            name='week9',
            field=models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=0, verbose_name='Week 9, V9 Fertigation Nitrogen'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
