# Generated by Django 5.1.2 on 2026-06-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_gameprofile_waterlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='yield_vs_et',
            field=models.FloatField(default=-1),
        ),
    ]
