# Generated by Django 5.1.2 on 2026-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_gameprofile_yield_vs_et'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='hybrid',
            field=models.CharField(choices=[('IB2074 Channel213-19VTPRIB', 'Channel213-19VTPRIB ($270/bag)'), ('IB2075 Fontanelle 11D637', 'Fontanelle 11D637 ($262/bag)'), ('IB2073 Pioneer 0801AM', 'Pioneer 0801AM ($225/bag)'), ('IB2072 Pioneer 1197AM', 'Pioneer 1197AM ($235/bag)'), ('IB1071 Pioneer 1366AML', 'Pioneer 1366AML ($243/bag)'), ('IB1073 Pioneer 1185', 'Pioneer 1185AM ($260/bag)')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='seeding_rate',
            field=models.IntegerField(choices=[(24000, 24000), (24500, 24500), (25000, 25000), (25500, 25500), (26000, 26000), (26500, 26500), (27000, 27000), (27500, 27500), (28000, 28000), (28500, 28500), (29000, 29000), (29500, 29500), (30000, 30000), (30500, 30500), (31000, 31000), (31500, 31500), (32000, 32000), (32500, 32500), (33000, 33000), (33500, 33500), (34000, 34000), (34500, 34500), (35000, 35000), (35500, 35500), (36000, 36000), (36500, 36500), (37000, 37000), (37500, 37500), (38000, 38000), (38500, 38500), (39000, 39000), (39500, 39500), (40000, 40000), (40500, 40500), (41000, 41000), (41500, 41500), (42000, 42000)], default=10000),
        ),
    ]
