# Generated by Django 5.1.2 on 2025-09-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_fertilizerinit_week1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='hybrid',
            field=models.CharField(choices=[('MZCER048', 'MZCER048'), ('IB1071', 'IB1071')], default=None, max_length=8, null=True),
        ),
    ]
