# Generated by Django 5.1.2 on 2026-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_gameprofile_hybrid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='profit',
            field=models.FloatField(default=-1),
        ),
    ]
