# Generated by Django 5.1.2 on 2025-09-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_gameprofile_hybrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='hybrid',
            field=models.CharField(choices=[('IB2074 Channel213-19VTPRIB', 'Channel213-19VTPRIB'), ('PC0006 Fontanelle 11D637', 'Fontanelle 11D637'), ('IB2073 PIO 0801AM', 'Pioneer 0801AM'), ('IB2072 PIO 1197AM', 'Pioneer 1197AM'), ('IB1071 PIO 1366AML', 'Pioneer 1366AML'), ('RandomG', 'RandomG')], default=None, max_length=30, null=True),
        ),
    ]
