# Generated by Django 5.1.2 on 2026-07-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_gameprofile_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
