# Generated by Django 5.1.2 on 2026-07-23 19:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_gameprofile_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='fertigation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, default=list, size=None),
        ),
    ]
