# Generated by Django 5.1.2 on 2026-08-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_gameprofile_fertigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='init_step',
            field=models.IntegerField(default=0),
        ),
    ]
