# Generated by Django 5.1.2 on 2025-10-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_gameprofile_hybrid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='team_id',
        ),
        migrations.AddField(
            model_name='gameprofile',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
