# Generated by Django 5.1.2 on 2025-11-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_remove_gameprofile_team_id_gameprofile_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='projected_yield',
            field=models.FloatField(default=0),
        ),
    ]
