# Generated by Django 5.1.2 on 2025-07-07 21:43

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='activation_key',
            field=models.CharField(default=None, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='key_expires',
            field=models.IntegerField(blank=True, default=time.time),
        ),
    ]
