# Generated by Django 5.1.2 on 2025-10-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
