# Generated by Django 5.1.2 on 2025-10-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
