# Generated by Django 5.1.2 on 2025-10-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='games',
        ),
        migrations.AddField(
            model_name='student',
            name='game',
            field=models.CharField(blank=True, default=list, max_length=256),
        ),
    ]
