# Generated by Django 5.1.2 on 2025-10-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_games_student_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tempPassword',
            field=models.BooleanField(default=True),
        ),
    ]
